name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: pnpm exec prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Setup PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "15"
          postgresql db: katas_test
          postgresql user: postgres
          postgresql password: postgres

      - name: Run database migrations
        run: pnpm exec prisma migrate deploy
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/katas_test?schema=public"

      - name: Run Playwright tests
        run: pnpm exec playwright test --reporter=line
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/katas_test?schema=public"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
